paths:
  csv_path: "./dataset/train.csv"
  img_dir: "./dataset/train_images"
  save_path: "./dataset/annotations.json"
  image_dir: "./data/images/"
  annotation_path: "./dataset/annotations.json"
  save_dir: "result/"
  path_visualize: "./visualize"
  save_dir_patches: "./patches/images"

image_params:
  img_width: 1600
  img_height: 256
  target_width: 518
  target_height: 518

processing_params:
  min_contour_area: 32
  min_bbox_size: 8
  class_ids: [1, 2, 3, 4]
  context: 0.2

extract_features:


training:
  max_images: null 
  max_patches_per_img: 5
  epochs_ssl: 3
  device: "cuda"  