paths:
  csv_path: "./dataset/train.csv"
  img_dir: "./dataset/train_images"
  save_path: "./dataset/annotations.json"
  annotation_path: "./dataset/annotations.json"
  save_dir: "result/"
  path_visualize: "./visualize"
  report_dir: "./report"


image_params:
  img_width: 1600
  img_height: 256
  target_width: 224
  target_height: 224

extract_patches:
  save_dir_patches: "./patches/images"
  annotation_path: "./patches/patches_annotation.json"
  min_contour_area: 32
  min_bbox_size: 8
  class_ids: [1, 2, 3, 4]
  context: 0.2
  max_patches_per_img: 5

extract_features:
  batch_size: 32
  target_size: 224


ssl_dino_finetune:
  target_size: 224
  epochs: 3
  batch_size: 32
  learning_rate: 1e-6
  weight_decay: 1e-4
  freeze_blocks: 10

training:
  max_images: null 
  epochs: 3
  models_dir: "./models"